/** @typedef {import('@tokiforge/core').DesignTokens} DesignTokens */

/** @type {import('@tokiforge/core').Plugin} */
export const framerTokensPlugin = {
  name: 'framer-style-ts',
  exporter(tokens) {
    const lines = [
      '// Auto-generated by TokiForge framer-style-ts exporter',
      'export const framerTheme = { cssVars: `\\',
    ];
    const vars = flattenColorVars(tokens);
    for (const [k, v] of Object.entries(vars)) {
      lines.push(`  --${k}: ${v};`);
    }
    lines.push('` as const };');
    lines.push('export default framerTheme;');
    return lines.join('\n');
  },
};

/** @param {DesignTokens} tokens */
function flattenColorVars(tokens) {
  const out = {};
  const walk = (obj, path) => {
    if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return;
    if ('value' in obj && typeof obj.type === 'string') {
      if (obj.type === 'color' && typeof obj.value === 'string') {
        const key = path.replace(/\./g, '-');
        out[key] = obj.value;
      }
      return;
    }
    for (const key of Object.keys(obj)) {
      walk(obj[key], path ? `${path}.${key}` : key);
    }
  };
  walk(tokens, '');
  return out;
}
