import * as fs from 'node:fs';
import * as path from 'path';
import { TokenParser, TokenExporter } from '@tokiforge/core';
import type { DesignTokens } from '@tokiforge/core';

interface DocsOptions {
  output?: string;
  title?: string;
  prefix?: string;
}

interface FlatTokenDoc {
  path: string;
  cssVar: string;
  value: string;
  type?: string;
  description?: string;
}

function collectTokens(
  tokens: DesignTokens,
  prefix: string,
  parentPath = ''
): FlatTokenDoc[] {
  const docs: FlatTokenDoc[] = [];

  for (const key of Object.keys(tokens)) {
    const value = (tokens as Record<string, unknown>)[key];
    if (!value || typeof value !== 'object') continue;

    const tokenPath = parentPath ? `${parentPath}.${key}` : key;
    const node = value as Record<string, unknown>;

    if ('value' in node) {
      const flat = TokenExporter.flattenTokens(
        { [key]: node } as DesignTokens,
        prefix + (parentPath ? `-${parentPath.replace(/\./g, '-')}` : '')
      );
      for (const [cssVar, cssValue] of Object.entries(flat)) {
        docs.push({
          path: tokenPath,
          cssVar: `--${cssVar.toLowerCase()}`,
          value: cssValue,
          type: node.type as string | undefined,
          description: node.description as string | undefined,
        });
      }
    } else {
      docs.push(...collectTokens(node as DesignTokens, prefix, tokenPath));
    }
  }

  return docs;
}

function isColorValue(doc: FlatTokenDoc): boolean {
  return (
    doc.type === 'color' ||
    /^#([0-9a-f]{3,8})$/i.test(doc.value) ||
    /^(rgb|hsl)a?\(/i.test(doc.value)
  );
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderRows(docs: FlatTokenDoc[]): string {
  return docs
    .map((doc) => {
      const preview = isColorValue(doc)
        ? `<span class="swatch" style="background:${escapeHtml(doc.value)}"></span>`
        : '';
      const description = doc.description
        ? `<div class="desc">${escapeHtml(doc.description)}</div>`
        : '';
      return `      <tr>
        <td>${preview}<code>${escapeHtml(doc.path)}</code>${description}</td>
        <td><code>${escapeHtml(doc.cssVar)}</code></td>
        <td><code>${escapeHtml(doc.value)}</code></td>
      </tr>`;
    })
    .join('\n');
}

export async function docsCommand(
  input: string = 'tokens.json',
  options: DocsOptions = {}
): Promise<void> {
  const { output = 'token-docs.html', title = 'Design Tokens', prefix = 'hf' } = options;

  const inputPath = path.resolve(process.cwd(), input);
  if (!fs.existsSync(inputPath)) {
    console.error(`Token file not found: ${inputPath}`);
    process.exit(1);
  }

  const tokens = TokenParser.parse(inputPath, { validate: true, expandReferences: true });
  const docs = collectTokens(tokens, prefix);

  const groups = new Map<string, FlatTokenDoc[]>();
  for (const doc of docs) {
    const group = doc.path.split('.')[0];
    const list = groups.get(group) ?? [];
    list.push(doc);
    groups.set(group, list);
  }

  const sections = Array.from(groups.entries())
    .map(
      ([group, groupDocs]) => `  <section>
    <h2>${escapeHtml(group)}</h2>
    <table>
      <thead><tr><th>Token</th><th>CSS variable</th><th>Value</th></tr></thead>
      <tbody>
${renderRows(groupDocs)}
      </tbody>
    </table>
  </section>`
    )
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, sans-serif; margin: 0 auto; max-width: 60rem; padding: 2rem 1rem; line-height: 1.5; }
    h1 { margin-bottom: 0.25rem; }
    .meta { color: #888; margin-bottom: 2rem; }
    section { margin-bottom: 2.5rem; }
    h2 { text-transform: capitalize; border-bottom: 1px solid #8884; padding-bottom: 0.25rem; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 0.4rem 0.5rem; border-bottom: 2px solid #8884; }
    td { padding: 0.4rem 0.5rem; border-bottom: 1px solid #8882; vertical-align: top; }
    code { font-size: 0.85rem; }
    .swatch { display: inline-block; width: 1rem; height: 1rem; border-radius: 3px; border: 1px solid #8884; margin-right: 0.5rem; vertical-align: -0.15rem; }
    .desc { color: #888; font-size: 0.8rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">${docs.length} tokens &middot; generated by TokiForge</p>
${sections}
</body>
</html>
`;

  const outputPath = path.resolve(process.cwd(), output);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, html);
  console.log(`Generated token docs: ${output} (${docs.length} tokens)`);
}
