import { useState, useMemo } from 'react';
import type { DesignTokens } from '@tokiforge/core';

interface FlatToken { path: string; value: unknown; type?: string; }

function flattenTokens(obj: DesignTokens, prefix = ''): FlatToken[] {
  const result: FlatToken[] = [];
  for (const key of Object.keys(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    const val = obj[key];
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      const node = val as Record<string, unknown>;
      if ('value' in node) {
        result.push({ path, value: node.value, type: node.type as string | undefined });
      } else {
        result.push(...flattenTokens(val as DesignTokens, path));
      }
    }
  }
  return result;
}

/** Build TypeScript token object string from a nested DesignTokens tree */
function buildTsObject(obj: DesignTokens, indent: string): string[] {
  const result: string[] = [];
  for (const key of Object.keys(obj)) {
    const val = obj[key];
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      const node = val as Record<string, unknown>;
      if ('value' in node) {
        result.push(`${indent}  '${key}': '${String(node.value)}',`);
      } else {
        result.push(`${indent}  '${key}': {`);
        result.push(...buildTsObject(val as DesignTokens, `${indent}  `));
        result.push(`${indent}  },`);
      }
    }
  }
  return result;
}

type ExportTarget = { id: string; icon: string; name: string; ext: string; desc: string; color: string; };

const TARGETS: ExportTarget[] = [
  { id: 'css',     icon: '🎨', name: 'CSS Variables',   ext: '.css',   desc: 'Custom properties',       color: 'rgba(6,182,212,0.15)'   },
  { id: 'scss',    icon: '💅', name: 'SCSS Variables',  ext: '.scss',  desc: 'Sass/SCSS variables',      color: 'rgba(245,158,11,0.15)'  },
  { id: 'tailwind',icon: '🌬️', name: 'Tailwind Config', ext: '.js',    desc: 'tailwind.config.js',       color: 'rgba(6,182,212,0.12)'   },
  { id: 'json',    icon: '📋', name: 'JSON Tokens',     ext: '.json',  desc: 'Design Tokens W3C format', color: 'rgba(124,58,237,0.15)'  },
  { id: 'ts',      icon: '💻', name: 'TypeScript',      ext: '.ts',    desc: 'TS constants + types',     color: 'rgba(59,130,246,0.15)'  },
  { id: 'react',   icon: '⚛️', name: 'React Theme',     ext: '.tsx',   desc: 'React context provider',   color: 'rgba(99,179,237,0.15)'  },
  { id: 'flutter', icon: '🐦', name: 'Flutter Tokens',  ext: '.dart',  desc: 'Dart constants',           color: 'rgba(2,132,199,0.15)'   },
  { id: 'swift',   icon: '🍎', name: 'SwiftUI',         ext: '.swift', desc: 'Swift Color/Font tokens',  color: 'rgba(239,68,68,0.12)'   },
];

function generateOutput(tokens: DesignTokens, target: string): string {
  const flat = flattenTokens(tokens);
  const toVarName = (path: string) => path.replace(/\./g, '-');
  const toCamel = (path: string) =>
    path.split('.').map((s, i) => (i === 0 ? s : s[0].toUpperCase() + s.slice(1))).join('');

  switch (target) {
    case 'css': {
      const lines = [':root {'];
      for (const t of flat) lines.push(`  --${toVarName(t.path)}: ${String(t.value)};`);
      lines.push('}');
      return lines.join('\n');
    }
    case 'scss': {
      return flat.map(t => `$${toVarName(t.path)}: ${String(t.value)};`).join('\n');
    }
    case 'json': {
      return JSON.stringify(tokens, null, 2);
    }
    case 'tailwind': {
      const colors: Record<string, string> = {};
      const spacing: Record<string, string> = {};
      for (const t of flat) {
        if (t.type === 'color' || String(t.value).startsWith('#')) {
          colors[toVarName(t.path)] = String(t.value);
        }
        if (t.type === 'dimension' && t.path.startsWith('spacing')) {
          const segments = t.path.split('.');
          const last = segments[segments.length - 1];
          spacing[last] = String(t.value);
        }
      }
      return `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6).replace(/^/gm, '      ').trim()},
      spacing: ${JSON.stringify(spacing, null, 6).replace(/^/gm, '      ').trim()},
    },
  },
};`;
    }
    case 'ts': {
      const lines = ['// Auto-generated by TokiForge', 'export const tokens = {'];
      lines.push(...buildTsObject(tokens, ''));
      lines.push('} as const;');
      lines.push('');
      lines.push('export type TokenPath = string;');
      return lines.join('\n');
    }
    case 'react': {
      return `// Auto-generated by TokiForge
import { createContext, useContext } from 'react';

export const tokens = ${JSON.stringify(tokens, null, 2)};

const ThemeContext = createContext(tokens);

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  return <ThemeContext.Provider value={tokens}>{children}</ThemeContext.Provider>;
}

export function useTokens() {
  return useContext(ThemeContext);
}`;
    }
    case 'flutter': {
      const colorLines = flat
        .filter(t => t.type === 'color' || String(t.value).startsWith('#'))
        .map(t => {
          const hex = String(t.value).replace('#', '');
          return `  static const Color ${toCamel(t.path)} = Color(0xFF${hex.toUpperCase()});`;
        });
      return `// Auto-generated by TokiForge
import 'package:flutter/material.dart';

class AppTokens {
${colorLines.join('\n')}
}`;
    }
    case 'swift': {
      const colorLines = flat
        .filter(t => t.type === 'color' || String(t.value).startsWith('#'))
        .map(t => {
          const hex = String(t.value).replace('#', '');
          const r = Number.parseInt(hex.slice(0, 2), 16) / 255;
          const g = Number.parseInt(hex.slice(2, 4), 16) / 255;
          const b = Number.parseInt(hex.slice(4, 6), 16) / 255;
          return `    static let ${toCamel(t.path)} = Color(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)})`;
        });
      return `// Auto-generated by TokiForge
import SwiftUI

struct AppTokens {
  struct Colors {
${colorLines.join('\n')}
  }
}`;
    }
    default:
      return '// Select an export format above';
  }
}

interface Props { tokens: DesignTokens; toast: (m: string, t?: 'success' | 'error' | 'info') => void; }

export default function ExportPanel({ tokens, toast }: Props) {
  const [selected, setSelected] = useState('css');
  const code = useMemo(() => generateOutput(tokens, selected), [tokens, selected]);
  const target = TARGETS.find(t => t.id === selected) ?? TARGETS[0];

  function copyCode() {
    navigator.clipboard.writeText(code).catch(() => { /* clipboard unavailable */ });
    toast('Code copied to clipboard!', 'success');
  }

  function downloadFile() {
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `tokiforge-tokens${target.ext}`;
    a.click();
    URL.revokeObjectURL(url);
    toast(`Downloaded tokens${target.ext}`, 'success');
  }

  const totalTokens = useMemo(() => flattenTokens(tokens).length, [tokens]);
  const colorCount  = useMemo(
    () => flattenTokens(tokens).filter(t => t.type === 'color' || String(t.value).startsWith('#')).length,
    [tokens]
  );

  return (
    <div style={{ padding: '2rem', maxWidth: 1000, margin: '0 auto' }}>
      <div className="tf-page-header" style={{ padding: '0 0 1.5rem', border: 'none', marginBottom: '1.5rem' }}>
        <div>
          <h1 className="tf-page-title">📦 Multi-Framework Export</h1>
          <p className="tf-page-subtitle">Export your design tokens to any framework or platform</p>
        </div>
      </div>

      {/* Target Grid */}
      <div className="tf-export-grid" style={{ marginBottom: '1.5rem' }}>
        {TARGETS.map(t => (
          <div
            key={t.id}
            className={`tf-export-target${selected === t.id ? ' selected' : ''}`}
            style={{ borderColor: selected === t.id ? 'var(--tf-brand-light)' : undefined }}
            onClick={() => setSelected(t.id)}
          >
            <div className="tf-export-target-icon">{t.icon}</div>
            <div className="tf-export-target-name">{t.name}</div>
            <div className="tf-export-target-desc">{t.ext} · {t.desc}</div>
            {selected === t.id && <span className="tf-badge tf-badge-brand" style={{ fontSize: '0.5625rem' }}>Selected</span>}
          </div>
        ))}
      </div>

      {/* Code Output */}
      <div className="tf-code-block">
        <div className="tf-code-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ fontSize: '1rem' }}>{target.icon}</span>
            <span className="tf-code-lang">{target.name} — {target.ext}</span>
            <span className="tf-badge tf-badge-success" style={{ fontSize: '0.5625rem' }}>Ready</span>
          </div>
          <div style={{ display: 'flex', gap: '0.375rem' }}>
            <button className="tf-btn tf-btn-ghost tf-btn-sm" onClick={copyCode}>📋 Copy</button>
            <button className="tf-btn tf-btn-primary tf-btn-sm" onClick={downloadFile}>⬇ Download</button>
          </div>
        </div>
        <div className="tf-code-body" style={{ maxHeight: 420, overflowY: 'auto', fontSize: '0.8125rem', lineHeight: 1.7 }}>
          <code style={{ color: 'var(--tf-text-code)' }}>{code}</code>
        </div>
      </div>

      {/* Export info */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))', gap: '0.75rem', marginTop: '1.5rem' }}>
        {[
          { label: 'Total Tokens', value: totalTokens,                          icon: '🪙' },
          { label: 'Color Tokens', value: colorCount,                           icon: '🎨' },
          { label: 'Output Size',  value: `${(code.length / 1024).toFixed(1)} KB`, icon: '📦' },
          { label: 'Export Format',value: target.name,                          icon: target.icon },
        ].map(s => (
          <div className="tf-stat-card" key={s.label}>
            <div style={{ fontSize: '1.25rem', marginBottom: '0.25rem' }}>{s.icon}</div>
            <div className="tf-stat-value" style={{ fontSize: '1.25rem' }}>{s.value}</div>
            <div className="tf-stat-label">{s.label}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
